/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ultralesson.apitesting;

import org.hamcrest.Matchers;
import org.testng.annotations.*;

import static io.restassured.RestAssured.given;
import static io.restassured.http.ContentType.JSON;
import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void testGetAllUsersAPI(){
        given()
                .when()
                .get("https://gorest.co.in/public/v2/users")
                .then()
                .statusCode(200)
                .log().body()
                .body("body",Matchers.hasSize(10));
    }

    @Test
    public void testAddNewUser(){
        given()
                .accept(JSON)
                .contentType(JSON)
                .header("Authorization","Bearer 8ed75a51d163800b750d03c69dc9c1a94c7eedb2c06642ad5c8377904a0d1a91")
                .body("{\n" +
                        "    \"name\": \"Tenali Ramakrishna\",\n" +
                        "    \"gender\": \"male\",\n" +
                        "    \"email\": \"tenali.ramakrishna54@1.com\",\n" +
                        "    \"status\": \"active\"\n" +
                        "}")
                .when()
                .post("https://gorest.co.in/public/v2/users")
                .then()
                .statusCode(201)
                .log().body()
                .body("id", Matchers.notNullValue())
                .body("email",Matchers.equalTo("tenali.ramakrishna54@1.com"));
    }
}
