/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ultralesson.apitesting;

import org.testng.annotations.*;

import static io.restassured.RestAssured.given;
import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void testGetAllUsersAPI(){
        given()
                .when()
                .get("https://gorest.co.in/public/v2/users")
                .then()
                .statusCode(200)
                .log().body();
    }
}
